#include <Arduino.h>
#ifndef MONITOR_LOG_H
#define MONITOR_LOG_H
//#define DEBUG_MODE
#define EVENT_MODE
#define ERROR_MODE
//#define DEBUG_MODE
void event_queue_handler();
void log_event(uint8_t module_ID, uint8_t type_ID, uint8_t event_ID, uint32_t time_stamp, uint16_t value);
enum type_ID : uint8_t
{
    DEBUG,
    EVENT,
    ERROR
};

#ifdef DEBUG_MODE
    #define LOG_DEBUG(MODULE_ID, EVENT_ID, TIME_STAMP, VALUE) log_event(MODULE_ID, DEBUG, EVENT_ID, TIME_STAMP, VALUE)
#else
    #define LOG_DEBUG(MODULE_ID, EVENT_ID, TIME_STAMP, VALUE)

#endif

#ifdef EVENT_MODE
    #define LOG_EVENT(MODULE_ID, EVENT_ID, TIME_STAMP, VALUE) log_event(MODULE_ID, EVENT, EVENT_ID, TIME_STAMP, VALUE)
#else
    #define LOG_EVENT(MODULE_ID, EVENT_ID, TIME_STAMP, VALUE)
#endif

#ifdef ERROR_MODE
    #define LOG_ERROR(MODULE_ID, EVENT_ID, TIME_STAMP, VALUE) log_event(MODULE_ID, ERROR, EVENT_ID, TIME_STAMP, VALUE)
#else
    #define LOG_ERROR(MODULE_ID, EVENT_ID, TIME_STAMP, VALUE)
#endif

enum module_ID : uint8_t
{
    ADC_,
    BUZZER,
    DIAL,
    TM1637,
    DOOR,
    HEAT_ELEMENT,
    OVEN_TIMER,
    SMOKE_SENSOR,
    TEMP_SENSOR,
    TIMER_BUTTONS,
    TIMER_COUNTER1

};
enum event_ID : uint8_t
{
    ADC_CONFIGURED,
    ADC_START_CONVERSION,
    BUZZER_CONFIGURED,
    BUZZER_SMOKE,
    BUZZER_TIMER,
    BUZZER_OFF,
    BUZZER_STATE_INVALID,
    DIAL_CONFIGURED,
    ADC_CONVERT_DONE,
    ADC_VALUE_ERROR,
    DIAL_TEMP_CHANGE,
    DISPLAY_CONFIGURED,
    DISPLAY_UPDATED,
    DOOR_CONFIGURED,
    DOOR_OPENED,
    DOOR_CLOSED,
    DOOR_TM_RESET,
    HEAT_ELEMENT_CONFIGURED,
    TEMP_EXCEEDED,
    TEMP_RECEEDED,
    HEAT_ELEMENT_ON,
    HEAT_ELEMENT_OFF,
    OVEN_TIMER_CONFIGURED,
    OVEN_TIMER_STOPPED,
    OVEN_TIMER_START_RESET,
    OVEN_TIMER_STARTED,
    MQ2_CONFIGURED,
    MQ2_HIGH,
    MQ2_LOW,
    TEMP_SENSOR_CONFIGURED,
    TEMP_SENSOR_CHANGE,
    TEMP_SENSOR_VALUE_ERROR,
    TEMP_SENSOR_CONVERT_DONE,
    TIMER_BUTTONS_CONFIGURED,
    TIMER_UP_PUSH,
    TIMER_DOWN_PUSH,
    TIMER_SR_PUSH,
    TIMER_COUNTER1_CONFIGURED,
    TIMER_COUNTER1_DISABLE,
    TIMER_COUNTER1_ENABLE,
    TIMER_STATE_CONFIG_ERROR,
    TIMER_VALUE_ERROR,
    DOOR_STATE_ERROR,
    SIGNAL_START_RESET
};
#endif